CREATE TABLE indexint(
   indexint_id      INTEGER  NOT NULL PRIMARY KEY 
  ,indexint_name    INTEGER  NOT NULL
  ,indexint_comment TEXT NOT NULL
  ,index_indexint   TEXT NOT NULL
  ,num_pclass       int(11)  NOT NULL
);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (1,0,'Información de comunicación','000 Información de comunicación',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (2,10,'Bibliografías Catálogos','010 catálogos de bibliografías',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (3,20,'Bibliotecas - y lectura, documentación','020 bibliotecas leyendo documentación',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (4,30,'Enciclopedias generales','030 enciclopedias generales',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (5,40,'X','040 x',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (6,50,'Publicaciones periódicas generales - directorios','050 directorios generales de publicaciones periódicas',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (7,60,'Organizaciones generales - congresos','060 congresos de organizaciones generales',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (8,70,'Edición de prensa','070 edición de prensa',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (9,80,'Colecciones - mezclas, discursos','080 colecciones de discursos mixtos',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (10,90,'Manuscritos Libros raros','090 manuscritos de libros raros',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (11,100,'Filosofía','100 filosofía',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (12,110,'Metafísico','110 metafísica',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (13,120,'Conocimiento','120 conocimiento',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (14,130,'Parapsicología - astrología, grafología','130 parapsicología astrología grafología',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (15,140,'Sistemas filosóficos','140 sistemas filosóficos',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (16,150,'Psicología','150 psicología',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (17,160,'Lógica','160 lógica',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (18,170,'Moral - ético','170 moral ética',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (19,180,'Filósofos antiguos y orientales','180 antiguos filósofos orientales',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (20,190,'Filósofos modernos - (siglo XVI hasta la actualidad)','190 filósofos modernos desde el siglo XVI hasta la actualidad',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (21,200,'Religión','200 religión',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (22,210,'Religión natural','210 religión natural',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (23,220,'Evangelios de la Biblia','220 evangelios de la biblia',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (24,230,'Teología doctrinal cristiana - (dogma)','230 dogma de la teología doctrinal cristiana',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (25,240,'Teología espiritual - vida religiosa','240 teología espiritual vida religiosa',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (26,250,'Teología pastoral','250 teología pastoral',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (27,260,'La Iglesia y la Sociedad Cristianas','260 sociedad de la iglesia cristiana',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (28,270,'Historia de la Iglesia Cristiana','270 historia de la iglesia cristiana',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (29,280,'Otras denominaciones cristianas','280 otras denominaciones cristianas',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (30,290,'Otras religiones y mitologías','290 mitologías de otras religiones',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (31,300,'Ciencias Sociales','300 ciencias sociales',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (32,310,'Estadísticas','310 estadísticas',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (33,320,'Política - El Estado','320 política estatal',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (34,330,'Economía: finanzas, producción, consumo','330 economía financiar producción consumo',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (35,340,'Ley - justicia','340 ley justicia',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (36,350,'Administración del Estado','350 administración estatal',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (37,360,'Ayuda Ayuda Rescate','360 auxilios asistencia salvamento',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (38,370,'Educación - enseñanza','370 educación enseñanza',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (39,380,'Comunicación de transporte comercial','380 comunicación de transporte comercial',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (40,390,'Trajes y folclore','390 trajes folclóricos',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (41,400,'Idioma','400 idiomas',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (42,410,'Lingüístico','410 lingüística',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (43,420,'idioma en Inglés','420 idioma ingles',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (44,430,'Lengua alemana','430 idioma alemón',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (45,440,'Lengua francesa - (diccionarios, gramática)','440 diccionarios de gramática del idioma francés',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (46,450,'idioma italiano','450 lengua italiana',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (47,460,'Idioma español y portugués','460 lengua española portuguesa',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (48,470,'latón','470 lengua latina',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (49,480,'lengua griega','480 idioma griego',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (50,490,'Otros idiomas: ruso, árabe ,?','490 otros idiomas',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (51,500,'Ciencias','500 ciencias',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (52,510,'Matemáticas','510 matemáticas',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (53,520,'Astronomía','520 astronomía',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (54,530,'Físico','530 físico',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (55,540,'Química - mineralogía','540 mineralogía química',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (56,550,'Ciencias de la Tierra - geología, meteorología','550 ciencias de la tierra geología meteorología',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (57,560,'Paleontología - (los fósiles)','560 paleontología fósil',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (58,570,'Ciencias de la vida: biología, genética','570 ciencias de la vida biología genética',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (59,580,'Botónica - (plantas)','580 plantas de botónica',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (60,590,'Zoología - (animales)','590 zoología animal',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (61,600,'Técnicas','600 técnicas',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (62,610,'Medicina - higiene, salud','610 medicina higiene salud',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (63,620,'Técnicas industriales: ¿mecánica, electricidad, radio, energía?','620 técnicas industriales electricidad mecónica energía de radio',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (64,630,'Agricultura: silvicultura, ganadería, pesca','630 agricultura forestal agricultura pesca',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (65,640,'Artes del hogar: cocina, corte y confección, tratamientos de belleza','640 artes del hogar cocina coser cuidado de la belleza',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (66,650,'Negocios: trabajo de oficina, ventas, publicidad','650 oficinas de trabajo comerciales venta publicidad',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (67,660,'Industrias química y alimentaria','660 industrias químicas alimentarias',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (68,670,'Fabricación industrial: metalurgia, madera, textil.','670 fabricaciones industriales madera metalurgia textil',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (69,680,'Artículos manufacturados','680 artículos manufacturados',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (70,690,'Construcción de edificio','690 construcción de edificios',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (71,700,'Arte y ocio','700 artes de ocio',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (72,710,'Urbanismo - arte del paisaje','710 paisaje de arte urbanístico',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (73,720,'Arquitectura','720 arquitectura',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (74,730,'Escultura','730 escultura',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (75,740,'Dibujo - artes decorativas','740 dibujo de artes decorativas',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (76,750,'Cuadro','750 pintura',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (77,760,'Artes gr+aficas - diseño gr+afico','760 artes gr+aficas diseño gr+afico',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (78,770,'Fotografía','770 fotografía',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (79,780,'Mísica','780 mísica',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (80,790,'Ocio: espectúculos, juegos, deportes','790 espectúculos de ocio juegos deportes',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (81,800,'Literatura','800 literatura',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (82,810,'Literatura americana','810 literatura americana',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (83,820,'Literatura inglesa','820 literatura inglesa',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (84,830,'Literatura alemana','830 literatura alemana',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (85,840,'literatura francés','840 literatura francesa',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (86,850,'Literatura italiana','850 literatura italiana',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (87,860,'Literatura española y portuguesa','860 Literatura española portuguesa',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (88,870,'Literatura latina','870 literatura latina',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (89,880,'Literatura griega','880 literatura griega',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (90,890,'Otras literaturas','890 otra literatura',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (91,900,'Geografía Historia','900 geografía de la historia',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (92,910,'Geografía - viajes','910 viajes de geografía',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (93,920,'Biografías: vida de un personaje, genealogía','920 biografías genealogía de personajes de vida',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (94,930,'Historia antigua','930 historia antigua',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (95,940,'Historia de Europa','940 historia de europa',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (96,950,'Historia de Asia','950 historia de asia',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (97,960,'Historia de Africa','960 historia africa',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (98,970,'Historia de América del Norte','970 historia de américa del norte',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (99,980,'Historia de Sudamérica','980 historia de américa del sur',1);
INSERT INTO indexint(indexint_id,indexint_name,indexint_comment,index_indexint,num_pclass) VALUES (100,990,'Historia de Oceanía','990 historia oceónica',1);
